name: Build and Upload

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # اضافه کردن تنظیم نسخه Node.js

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build executable
        run: pyinstaller --onefile --windowed --icon=logo3.ico KeySwitchFix1.0.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: my-executable
          path: dist/
